%% This function calculates the root mean squared deviation (RMSD) for each location on the dataset by
% incorporating a varying number of principal components (PCs) into the equation. 
% It also reshapes and logs the residuals to analyze them spatially.
% When Num_PCs = 2 and n = 2, the figure generated by this function is the image from
%       Figure 4B in the manuscript
%
% Inputs 
%   AverageCVall -> 1x2 cell storing the average CV for each of the two datasets
%   n -> changing this number to either 1 or 2 will determine which dataset
%   Flat_cell ->  1x2 cell storing flattened dataset from each of the datasets
%       from varnames
%   coeff_cell -> 1x2 cell storing coefficients from pca for each dataset
%   score_cell -> 1x2 cell storing the scores from pca for each dataset
%   Num_PCs -> number of PCs incorporated into the equation
%   NEWEDIT -> edited dataset. This is used for the size of the X Y
%       coordinates.
%
% Output
%
%   roots -> root mean squared error for each location 
%   resi_reshape -> roots but resized to fit the x and y sizes
%   resi_reshape_l -> log10 of resi_reshape
%   mean_resi -> Mean of the RMSD values (in pA), summarizing the overall reconstruction error
%   resi_sd -> Standard deviation of the RMSD values (in pA), indicating variability in the error
%   RecreatedFlattenedImage -> voltammogram made from PCA
%
%Code written by: Rudy R. Acosta, Univeristy of Arkansas, 08/15/24

function [roots,actual_residuals, resi_reshape,resi_reshape_l, mean_resi, resi_sd,RecreatedFlattenedImage] = RMSD(AverageCVall,n,Flat_cell,score_cell,coeff_cell,Num_PCs,Voltametric_Data_LR,applied_potentials,VoltammogramNumber)
%Rebuild voltammograms from their scores
RecreatedFlattenedImage=zeros(size((Flat_cell{1,n})));
    for j=1:size(Flat_cell{1,n},1)
 for i=1:Num_PCs
           RecreatedFlattenedImage(j,:) = AverageCVall{n}+(-score_cell{1,n}(j,1:Num_PCs)*-coeff_cell{1,n}(:,1:Num_PCs)'); %:Num_PCs
 end
    end

% Define residuals
roots = zeros(size(RecreatedFlattenedImage,1),1);
loops = size(Flat_cell{1,n},1);

for L = 1:loops
measured = Flat_cell{1,n}(1:L,:);
pc_recon = RecreatedFlattenedImage(1:L,:);

roots = rmse(pc_recon,measured,2);

actual_residuals = pc_recon - measured;
end

resi_reshape=reshape(roots,[size(Voltametric_Data_LR,1),size(Voltametric_Data_LR,2)]);
resi_reshape_l=log10(resi_reshape);

figure('Position', [400,160,560,520]);
imagesc(rot90(resi_reshape)*1000)
     set(gca,'XTick',[],'YTick',[],'FontSize',45,'Position' , [0.01,0.11,0.714107142857143,0.815])
   
colormap hot
colorbar
axis tight

% Colorbar in pA
hColorbar=colorbar;
hColorbar.FontSize=30;
clim([0 39])
hColorbar.Label.String='{\it RMSD} / pA';

hColorbar.FontSize = 35;
hColorbar.LineWidth = 4;
hColorbar.Position = [0.748220906544427,0.111904761904762,0.055350522027002,0.806978653530377];


mean_resi = mean(mean(resi_reshape))*1000;
resi_sd = std(std(resi_reshape))*1000;

figure('Position', [1,1,810,640]);
hold on
plot(applied_potentials{n}, Flat_cell{n}(VoltammogramNumber,:), 'LineStyle', '-','LineWidth', 6, 'Color', [0 0 0]);
plot(applied_potentials{n}, RecreatedFlattenedImage(VoltammogramNumber,:), 'LineStyle', '--', 'LineWidth', 6, 'Color', [1 0 0]);
ax = gca;
set(gca,'FontName','Helvetica','FontSize',70)
ax.LineWidth = 6;
xlabel('{\it E} vs Ag/AgCl, V')
ylabel(['{\it i}' ' / nA'])
xlim([-0.6 1.05])
ylim([-1.3 0.6])

end
